version: '3.3'
services:
  db:
    image: postgres
    container_name: maharshi_postgres
    environment:
      #HOST: localhost
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postman
    volumes:
      - ./data
    expose:
      - 5432
    ports:
      - 5432:5432
  mypython:
    container_name: maharshi_python
    depends_on:
       - db
    build: ./
    command: python3 CSVtoDB.py -c configurations/configurations.txt
    ports:
      - 8000:8000
